# Generated by Django 4.2.6 on 2024-05-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
