# Generated by Django 4.2.6 on 2024-05-22 16:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='item__name', unique=True)),
                ('transaction_date', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('payment_method', models.CharField(blank='True', choices=[('MP', 'MPESA'), ('VISA', 'VISA'), ('CS', 'CASH'), ('VM', 'VOOMA'), ('BK', 'BANK')], max_length=20, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('amount_received', models.FloatField(default=False)),
                ('balance', models.FloatField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Served by')),
            ],
        ),
    ]
