# Generated by Django 4.2.6 on 2024-05-23 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(blank=True, default=datetime.date.today)),
                ('initial_stock', models.IntegerField(blank=True, default=0.0)),
                ('damage', models.IntegerField(blank=True, default=0.0)),
                ('withdrawal', models.IntegerField(blank=True, default=0.0)),
                ('delivery', models.IntegerField(blank=True, default=0.0)),
                ('sales', models.IntegerField(blank=True, default=0.0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Served by')),
            ],
            options={
                'verbose_name_plural': 'Iventory Reports',
            },
        ),
    ]
