# Generated by Django 4.2.6 on 2024-05-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
