# Generated by Django 4.2.6 on 2024-05-22 15:58

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_sale_customer_name_delete_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='item__name', unique=True),
        ),
    ]
